return {
    "nvim-treesitter/nvim-treesitter", -- nvim-treesitter replacement
    run = ":TSUpdate",
    config = function()
        local cfg = {
            ensure_installed = {
                "asm",
                "bash",
                "c",
                "c_sharp",
                "cmake",
                "cpp",
                -- "crystal",
                "css",
                "csv",
                "diff",
                "dockerfile",
                "embedded_template",
                "gdscript",
                "gdshader",
                "git_config",
                "git_rebase",
                "gitattributes",
                "gitcommit",
                "gitignore",
                "go",
                "gomod",
                "gosum",
                "hjson",
                "html",
                "ini",
                "java",
                "javascript",
                "json",
                "jsonc",
                "latex",
                "lua",
                "make",
                "markdown",
                "markdown_inline",
                "meson",
                "nginx",
                "python",
                "query",
                "ron",
                "ruby",
                "rust",
                "scheme",
                "scss",
                "sql",
                "toml",
                "tsx",
                "typescript",
                "vim",
                "vimdoc",
                "xml",
                "yaml",
            },
            highlight = {
                enable = true,
                additional_vim_regex_highlighting = false,
            },
            indent = {
                enable = false,
            },
            endwise = {
                enable = true,
            },
        }

        vim.treesitter.language.register("xml", "csproj")

        require("nvim-treesitter").setup(cfg)
    end,
}
