return {
    "romus204/tree-sitter-manager.nvim", -- nvim-treesitter replacement
    config = function()
        local cfg = {
            ensure_installed = {
                "asm",
                "bash",
                "c",
                "c_sharp",
                "cmake",
                "cpp",
                -- "crystal",
                "css",
                "csv",
                "diff",
                "dockerfile",
                "embedded_template",
                "gdscript",
                "gdshader",
                "git_config",
                "git_rebase",
                "gitattributes",
                "gitcommit",
                "gitignore",
                "go",
                "gomod",
                "gosum",
                "hjson",
                "html",
                "ini",
                "java",
                "javascript",
                "json",
                "jsonc",
                "latex",
                "lua",
                "make",
                "markdown",
                "markdown_inline",
                "meson",
                "nginx",
                "python",
                "query",
                "ron",
                "ruby",
                "rust",
                "scheme",
                "scss",
                "sql",
                "toml",
                "tsx",
                "typescript",
                "vim",
                "vimdoc",
                "xml",
                "yaml",
            },
            highlight = true,
            languages = {
                cmake = {
                    install_info = {
                        url = "https://github.com/tree-sitter-grammars/tree-sitter-make",
                        queries = "queries",
                    },
                },
            },
        }

        require("tree-sitter-manager").setup(cfg)
    end,
}
